name: Build and attach artifacts

on:
  workflow_dispatch:

jobs:
  build-linux-x64:
    name: Build binary (linux-x64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run compile --target=bun-linux-x64 --define "VERSION=v1.0.0" --outfile dist/filen-cli-v1.0.0-linux-x64
      - name: Execute binary
        run: dist/filen-cli-linux-x64 --skip-update --help
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: filen-cli-linux-x64
          path: dist/filen-cli-linux-x64